# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins

title: Yuncheng Hao
description: Welcome to my homepage. You can find my info here.
show_downloads: true
# github:
#   zip_url: http://example.com/download.zip
